task: detection

evaluator:
  type: CocoEvaluator
  iou_types: ['bbox', ]

num_classes: 777 # your dataset classes
remap_mscoco_category: False

train_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/fisheye8k-visdrone-vipcupnight2k-grayscalyololabel/fisheye8K_visdrone_vipcupnight2k_grayscale/train/images
    ann_file: /kaggle/input/fisheye8k-visdrone-vipcupnight2k-grayscalyololabel/fisheye8K_visdrone_vipcupnight2k_grayscale/train/train.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: True
  num_workers: 4
  drop_last: True
  collate_fn:
    type: BatchImageCollateFunction


val_dataloader:
  type: DataLoader
  dataset:
    type: CocoDetection
    img_folder: /kaggle/input/fisheye8k-visdrone-vipcupnight2k-grayscalyololabel/fisheye8K_visdrone_vipcupnight2k_grayscale/val/images
    ann_file: /kaggle/input/fisheye8k-visdrone-vipcupnight2k-grayscalyololabel/fisheye8K_visdrone_vipcupnight2k_grayscale/val/val.json
    return_masks: False
    transforms:
      type: Compose
      ops: ~
  shuffle: False
  num_workers: 4
  drop_last: False
  collate_fn:
    type: BatchImageCollateFunction
